#service url to to update emp details on PSA end
myden.mydenPsaInteg.service.url.emp.update=https://devapps.denave.com:8445/newMyDen-PSAInteg/updateEmpOnPSA
#service url to to update resigned emp details on PSA end
myden.mydenPsaInteg.service.url.resigned.emp.update=https://devapps.denave.com:8445/newMyDen-PSAInteg/updateResignedEmpOnPSA

myden.emp.empCode=employeeCode
myden.emp.employeeName=employeeName
myden.emp.employeeType=employeeType
myden.emp.projectNature=projectNature
myden.emp.companyId=companyId
myden.emp.emailId=emailId
myden.emp.countryId=countryId
myden.emp.designationId=designationId
myden.emp.reportingManager=reportingManager
myden.emp.jobId=jobId
myden.emp.roleId=roleId
myden.emp.postingCity=postingCity
myden.emp.workingStatusId=workingStatusId
myden.emp.dateOfLeaving=dateOfLeaving
myden.emp.dateOfResignation=dateOfResignation

#########################
# APPLICATION DEPLOYMENT ENVIROMENT
app.deploy.envt = dev

#################################
data.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#######################

# DEV DB PROPERTIES
dev.data.url=jdbc:sqlserver://;databaseName=myden
dev.data.username=
dev.data.password=
dev.get.fileSave.env.location=D://myden//filesaver//

#################################################3

#Offer Letter DB Name
myden.offerLetterDbName=
myden.smtp.mail.userName=
myden.pmdp.mail.from=
myden.smtp.mail.userPassword=

# todoz - important - smtp server changed for testing.
myden.smtp.mail.smtpServerName=mail.denave.com
myden.smtp.mail.smtpServerPort=25
myden.smtp.auth.enable=true
myden.smtp.starttls.enable=false
myden.freemarker.template.path=/WEB-INF/mailTemplates/
myden.pmdp.enable.mail=true
myden.pmdp.mail.to=
myden.pmdp.mail.cc=
myden.pmdp.mail.bcc=
myden.pmdp.mail.hr.spoc=
myden.pmdp.mail.hr.spoc.malaysia=
myden.pmdp.mail.developer.spoc = 
myden.pmdp.server.file.download.url=D:/myden/PMDPDoc/FilesReceived/attachment
myden.pmdp.loginTomyDEN.LoginURL=https://devapps.denave.com:8445/myDEN

#DEV
dev.newmyden.to.oldmyden.token.validation.url=https://devapps.denave.com:8445/myDEN/NewMyDenLogin

myden.kra.setting.quaterly.draft.stages = 29,36,43,50
myden.stage.kra.quaterly.approval.notinitiated.at.rm=30,37,44,51
myden.stage.at.target.achieved=31,38,45,52
myden.stage.compentency.acceptance=61,62,63,64
myden.stage.initiated.rm=57,58,59,60
myden.stage.initiated.self.review=32,39,46,53
myden.stage.initiated.self.review.initiated=33,40,47,54
myden.stage.initiated.manager.review=34,41,48,55
myden.stage.initiated.manager.review.initiated=35,42,49,56
myden.stage.initiated.self.review.approval=65,66,67,68

dev.regularisation.reject.test.email.id = 

######POLICY
dev.old.myden.url=https://devapps.denave.com:8445/myDEN

myden.policy.description.India=India_V1
myden.policy.description.Singapore=Singapore_V1
myden.policy.description.UK=UK_V1
myden.policy.description.Malaysia=Malaysia_V1
myden.policy.description.Korea=Korea_V1

#Batch Update Files Location
batch.update.path.dev = D://myden//Batch//MyDENBatchUpdate

#Batch Update Header Count
batch.update.header.count.template.1=12
batch.update.header.count.template.2=11
batch.update.header.count.template.3=12
batch.update.header.count.template.4=7
batch.update.header.count.template.5=11
batch.update.header.count.template.6=7
batch.update.header.count.template.7=11
batch.update.header.count.template.8=17
batch.update.header.count.template.9=6
batch.update.header.count.template.10=8
batch.update.header.count.template.11=12
batch.update.header.count.template.12=10
batch.update.header.count.template.13=7
batch.update.header.count.template.14=8
batch.update.header.count.template.15=13
batch.update.header.count.template.16=13

#Date for new Policy added 
policy.added.static.date=2025-03-11

#CTC Updete Files Location
ctc.update.path.dev = D://myden//MyDENCTCUpdate
ctc.update.header.count.template=44

#FNF Update Files Location
fnf.update.path.dev = D://MyDENFNFUpdate
fnf.upload.header.count.template=15

#deepvue Update Files Location
deepvue.update.path.dev = D://MyDEN_Deepvue_UPLOAD
deepvue.upload.header.count.template=7

#OFFER LETTER UPLOAD Files Location
offerletter.upload.path.dev = D://myden//MyDEN_OFFERLETTER_UPLOAD
offerletter.upload.header.count.template=95

#Bank Cheque UPLOAD Files Location
bank.cheque.upload.path.dev = D://myden//MyDEN_BANKCHEQUE_UPLOAD

# SSOToken Database Details
databaseSSOToken.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
databaseSSOToken.url=jdbc:sqlserver://;databaseName=
databaseSSOToken.user=
databaseSSOToken.password=

#offer letter
com.denave.NSN.PISREF=
com.denave.NSN.SenderMailConfirmEntity=
com.denave.NSN.CCtoDenaveConfirmEntity=
com.denave.NSN.ConfirmEntityPath=

testuat.prospect.mail.to=
testuat.prospect.mail.cc=
it.prospect.mail.to=
it.prospect.mail.cc=

#myapps *************************************
## DenCRM (India)
dev.india.dencrm.url=https://devapps.denave.com:8441/DenCRM/login?

## DenCRM UK
dev.uk.dencrm.url=https://devapps.denave.com:8444/DenCRMUK/login?


## DenCRM (MY)
dev.my.dencrm.url=https://devapps.denave.com:8445/DenCRMMalaysia/login?

## BDCRM
dev.my.bdcrm.url=https://devapps.denave.com:8448/BDCRM/login?

## SICRM
dev.my.sicrm.url=https://devapps.denave.com:2082/GoogleISV/login?

## for  Envt (CRMBASIC-Amazon)
dev.IAM.url=https://devapps.denave.com:8245/iam/api/v1/login
dev.my.crmbasic.url=https://devapps.denave.com:5001/#/login

#end myapps
myden.root.url=https://devapps.denave.com:8445
myden.prospectimages.url = /myDEN/includes/img/offerletter/

testuat.prospect.mail.to=
testuat.prospect.mail.cc=
it.prospect.mail.to=
it.prospect.mail.cc=

myden.siteadmin.mail.finance.spoc=
myden.teamhrops.mail=
myden.teamhropsmalayia.mail=